# This is a basic workflow to help you get started with Actions

name: CI - Windows

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    paths-ignore: 
      - 'Docs/**'
  pull_request:
    branches: [ master ]
    paths-ignore: 
      - 'Docs/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@master

  # Setup MSBuild.exe path if required
    - name: Setup Environment
      uses: warrenbuckley/Setup-MSBuild@v1

    - name: Build Project F
      run: msbuild RTS-Solution.sln
